version: '3.8'

services:
  flower-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8080:8080"
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/flower-shop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
    networks:
      - flower-net

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: flower-shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - flower-db-data:/var/lib/postgresql/data
    networks:
      - flower-net

volumes:
  flower-db-data:

networks:
  flower-net:
    driver: bridge
